# Generated by Django 5.0.4 on 2024-04-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True)),
                ('Dietary_restriction', models.CharField(blank=True)),
                ('arrival_date', models.CharField(blank=True)),
                ('access_level', models.CharField(max_length=100)),
                ('additional_guest', models.CharField(blank=True)),
                ('additional_guest_first_name', models.CharField(blank=True)),
                ('additional_guest_last_name', models.CharField(blank=True)),
                ('additional_guest_dietary_restriction', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('dress_code', models.CharField(max_length=100)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwigwe.venue')),
            ],
        ),
    ]
