# Generated by Django 5.0.4 on 2024-04-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwigwe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='additional_guest',
            field=models.CharField(max_length=100),
        ),
    ]
