# Generated by Django 5.0.4 on 2024-04-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwigwe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='restriction',
            new_name='Dietary_restriction',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='guest',
            name='arrival_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True),
        ),
    ]
