# Generated by Django 5.0.4 on 2024-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwigwe', '0002_alter_guest_additional_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(default=False),
        ),
    ]
