# Generated by Django 5.0.4 on 2024-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwigwe', '0003_guest_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='not_attending',
            field=models.BooleanField(default=False),
        ),
    ]
